/*
 * MainSeparador.java
 *
 * Created on 20 de marzo de 2009, 22:09
 */
package es.logongas.lego.clasificador;

import es.logongas.lego.MotorDirection;
import es.logongas.lego.clasificador.modelo.Motor;
import es.logongas.lego.clasificador.modelo.SensorColor;
import es.logongas.lego.clasificador.modelo.SensorPosicion;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.SwingUtilities;

/**
 *
 * @author Administrador
 */
public class ViewClasificador extends javax.swing.JDialog implements ActionListener {

    MainComponentes mainComponentes;

    /**
     * Creates new form MainSeparador
     */
    public ViewClasificador(MainComponentes mainComponentes) {
        this.mainComponentes = mainComponentes;
        initComponents();
        clearAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelBrickCaidoSalida1 = new javax.swing.JLabel();
        jLabelBrickInicial = new javax.swing.JLabel();
        jLabelBrickColor = new javax.swing.JLabel();
        jLabelFlechaMotorSalida1 = new javax.swing.JLabel();
        jLabelBrickAntesColor = new javax.swing.JLabel();
        jLabelFlechaMotorCintaTransportadora = new javax.swing.JLabel();
        jLabelBrickSalida1 = new javax.swing.JLabel();
        jLabelFlechaSensorPosicionColor = new javax.swing.JLabel();
        jLabelBrickAntesSalida1 = new javax.swing.JLabel();
        jLabelFlechaSensorPosicionSalida1 = new javax.swing.JLabel();
        jLabelBrickAntesSalida2 = new javax.swing.JLabel();
        jLabelFlechaSensorPosicionSalida2 = new javax.swing.JLabel();
        jLabelBrickSalida2 = new javax.swing.JLabel();
        jLabelFlechaSensorPosicionInicio = new javax.swing.JLabel();
        jLabelBrickCaidoSalida2 = new javax.swing.JLabel();
        jLabelFlechaSensorColor = new javax.swing.JLabel();
        jLabelFlechaMotorSalida2 = new javax.swing.JLabel();
        jLabelDibujoCintaMetrica = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(212, 208, 201));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelBrickCaidoSalida1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/logongas/lego/clasificador/img/brick4x2.gif"))); // NOI18N
        jPanel1.add(jLabelBrickCaidoSalida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, -1, -1));

        jLabelBrickInicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/logongas/lego/clasificador/img/brick4x2.gif"))); // NOI18N
        jPanel1.add(jLabelBrickInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 300, -1, -1));

        jLabelBrickColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/logongas/lego/clasificador/img/brick4x2.gif"))); // NOI18N
        jPanel1.add(jLabelBrickColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, -1, -1));

        jLabelFlechaMotorSalida1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/logongas/lego/clasificador/img/flechaRoja.png"))); // NOI18N
        jPanel1.add(jLabelFlechaMotorSalida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, -1));

        jLabelBrickAntesColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/logongas/lego/clasificador/img/brick4x2.gif"))); // NOI18N
        jPanel1.add(jLabelBrickAntesColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, -1, -1));

        jLabelFlechaMotorCintaTransportadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/logongas/lego/clasificador/img/flechaRoja.png"))); // NOI18N
        jPanel1.add(jLabelFlechaMotorCintaTransportadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, -1, -1));

        jLabelBrickSalida1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/logongas/lego/clasificador/img/brick4x2.gif"))); // NOI18N
        jPanel1.add(jLabelBrickSalida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, -1, -1));

        jLabelFlechaSensorPosicionColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/logongas/lego/clasificador/img/flechaAzul.png"))); // NOI18N
        jPanel1.add(jLabelFlechaSensorPosicionColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, -1, -1));

        jLabelBrickAntesSalida1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/logongas/lego/clasificador/img/brick4x2.gif"))); // NOI18N
        jPanel1.add(jLabelBrickAntesSalida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, -1, -1));

        jLabelFlechaSensorPosicionSalida1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/logongas/lego/clasificador/img/flechaAzul.png"))); // NOI18N
        jPanel1.add(jLabelFlechaSensorPosicionSalida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));

        jLabelBrickAntesSalida2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/logongas/lego/clasificador/img/brick4x2.gif"))); // NOI18N
        jPanel1.add(jLabelBrickAntesSalida2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

        jLabelFlechaSensorPosicionSalida2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/logongas/lego/clasificador/img/flechaAzul.png"))); // NOI18N
        jPanel1.add(jLabelFlechaSensorPosicionSalida2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        jLabelBrickSalida2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/logongas/lego/clasificador/img/brick4x2.gif"))); // NOI18N
        jPanel1.add(jLabelBrickSalida2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        jLabelFlechaSensorPosicionInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/logongas/lego/clasificador/img/flechaAzul.png"))); // NOI18N
        jPanel1.add(jLabelFlechaSensorPosicionInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 80, -1, -1));

        jLabelBrickCaidoSalida2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/logongas/lego/clasificador/img/brick4x2.gif"))); // NOI18N
        jPanel1.add(jLabelBrickCaidoSalida2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, -1));

        jLabelFlechaSensorColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/logongas/lego/clasificador/img/flechaAzul.png"))); // NOI18N
        jPanel1.add(jLabelFlechaSensorColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, -1, -1));

        jLabelFlechaMotorSalida2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/logongas/lego/clasificador/img/flechaRoja.png"))); // NOI18N
        jPanel1.add(jLabelFlechaMotorSalida2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        jLabelDibujoCintaMetrica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/logongas/lego/clasificador/img/Cintametrica.png"))); // NOI18N
        jPanel1.add(jLabelDibujoCintaMetrica, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void clearAll() {
        clearBrick();
        jLabelFlechaMotorSalida2.setVisible(false);
        jLabelFlechaSensorColor.setVisible(false);
        jLabelFlechaSensorPosicionInicio.setVisible(false);
        jLabelFlechaSensorPosicionSalida2.setVisible(false);
        jLabelFlechaSensorPosicionSalida1.setVisible(false);
        jLabelFlechaSensorPosicionColor.setVisible(false);
        jLabelFlechaMotorCintaTransportadora.setVisible(false);
        jLabelFlechaMotorSalida1.setVisible(false);
    }
    public void clearBrick() {
        jLabelBrickCaidoSalida1.setVisible(false);
        jLabelBrickInicial.setVisible(false);
        jLabelBrickColor.setVisible(false);
        jLabelBrickAntesColor.setVisible(false);
        jLabelBrickSalida1.setVisible(false);
        jLabelBrickAntesSalida1.setVisible(false);
        jLabelBrickAntesSalida2.setVisible(false);
        jLabelBrickSalida2.setVisible(false);
        jLabelBrickCaidoSalida2.setVisible(false);
    }    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelBrickAntesColor;
    private javax.swing.JLabel jLabelBrickAntesSalida1;
    private javax.swing.JLabel jLabelBrickAntesSalida2;
    private javax.swing.JLabel jLabelBrickCaidoSalida1;
    private javax.swing.JLabel jLabelBrickCaidoSalida2;
    private javax.swing.JLabel jLabelBrickColor;
    private javax.swing.JLabel jLabelBrickInicial;
    private javax.swing.JLabel jLabelBrickSalida1;
    private javax.swing.JLabel jLabelBrickSalida2;
    private javax.swing.JLabel jLabelDibujoCintaMetrica;
    private javax.swing.JLabel jLabelFlechaMotorCintaTransportadora;
    private javax.swing.JLabel jLabelFlechaMotorSalida1;
    private javax.swing.JLabel jLabelFlechaMotorSalida2;
    private javax.swing.JLabel jLabelFlechaSensorColor;
    private javax.swing.JLabel jLabelFlechaSensorPosicionColor;
    private javax.swing.JLabel jLabelFlechaSensorPosicionInicio;
    private javax.swing.JLabel jLabelFlechaSensorPosicionSalida1;
    private javax.swing.JLabel jLabelFlechaSensorPosicionSalida2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public void actionPerformed(ActionEvent e) {
        
        
        Object source = e.getSource();
        if (source instanceof Motor) {
            Motor motor = (Motor) source;
            boolean visible = ((e.getID() == 1) ? true : false);
            MotorDirection motorDirection=MotorDirection.valueOf(e.getActionCommand());
            switch (motor.getPin()) {
                case 1:
                    jLabelFlechaMotorCintaTransportadora.setVisible(visible);
                    break;
                case 2:
                    jLabelFlechaMotorSalida1.setVisible(visible);
                    if (visible==true) {
                        clearBrick();
                        if (motorDirection==MotorDirection.Forward) {
                            jLabelBrickSalida1.setVisible(true);
                        } else {
                            jLabelBrickCaidoSalida1.setVisible(true);
                        }
                    } else {
                        clearBrick();
                    }                    
                    break;
                case 3:
                    jLabelFlechaMotorSalida2.setVisible(visible);
                    if (visible==true) {
                        clearBrick();
                        if (motorDirection==MotorDirection.Forward) {
                            jLabelBrickSalida2.setVisible(true);
                        } else {
                            jLabelBrickCaidoSalida2.setVisible(true);
                        }                        
                    } else {
                        clearBrick();
                    } 
                    break;
            }
        } else if (source instanceof SensorPosicion) {
            SensorPosicion sensorPosicion = (SensorPosicion) source;
            boolean visible = ((e.getID() == 0) ? true : false);
            switch (sensorPosicion.getPin()) {
                case 1:
                    jLabelFlechaSensorPosicionInicio.setVisible(visible);
                    if (visible==true) {
                         clearBrick();
                    } else {
                        clearBrick();
                        jLabelBrickInicial.setVisible(true);
                    }
                    break;
                case 2:
                    jLabelFlechaSensorPosicionColor.setVisible(visible);
                    if (visible==true) {
                         clearBrick();
                        jLabelBrickAntesColor.setVisible(true);
                    } else {
                        clearBrick();
                        jLabelBrickColor.setVisible(true);
                    }
                    break;
                case 3:
                    jLabelFlechaSensorPosicionSalida1.setVisible(visible);
                    if (visible==true) {
                         clearBrick();
                        jLabelBrickAntesSalida1.setVisible(true);
                    } else {
                        clearBrick();
                        jLabelBrickSalida1.setVisible(true);
                    }
                    break;
                case 4:
                    jLabelFlechaSensorPosicionSalida2.setVisible(visible);
                    if (visible==true) {
                         clearBrick();
                        jLabelBrickAntesSalida2.setVisible(true);
                    } else {
                        clearBrick();
                        jLabelBrickSalida2.setVisible(true);
                    }                    
                    break;
            }
        } else if (source instanceof SensorColor) {
            boolean visible = ((e.getID() == 1) ? true : false);
            jLabelFlechaSensorColor.setVisible(visible);
            clearBrick();
            jLabelBrickColor.setVisible(true);
        }
        /*        
         jLabelBrickCaidoSalida1.setVisible(false);
         
         jLabelBrickColor.setVisible(false);
         j
         jLabelBrickSalida1.setVisible(false);
         jLabelBrickAntesSalida1.setVisible(false);
         jLabelBrickAntesSalida2.setVisible(false);
         jLabelBrickSalida2.setVisible(false);
         jLabelBrickCaidoSalida2.setVisible(false);
         */

    }
}
